const recipes: Recipe[] = [
  {
    id: 1,
    name: 'Cheesy Risoli',
    ingredients: [
      '1 cup arborio rice',
      '2 1/2 cups chicken or vegetable broth',
      '1/2 cup grated Parmesan cheese',
      '1/2 cup mozzarella cheese, shredded',
      '1/2 cup breadcrumbs',
      '2 eggs, beaten',
      'Salt and pepper to taste',
      'Oil for frying',
      'Marinara sauce for dipping',
    ],
    image: '/assets/Img/food/f1.jpg',
    date: 1712645435,
    likes: 300,
    type: 2,
  },
  {
    id: 2,
    name: 'Delicious Pasta',
    ingredients: [
      '200 grams of pasta',
      '2 cups of water',
      '1 spoon of salt',
      '1 spoon of olive oil',
      '100 grams of parmesan cheese',
      '200 grams of tomato sauce',
    ],
    image: '/assets/Img/food/f2.jpg',
    date: 1712645416,
    likes: 200,
    type: 2,
  },
  {
    id: 3,
    name: 'Tasty Pizza',
    ingredients: [
      '1 pizza dough',
      '1 cup of tomato sauce',
      '1 cup of mozzarella cheese',
      '100 grams of pepperoni',
      '1 spoon of olive oil',
      '1 pinch of salt',
    ],
    image: '/assets/Img/food/f3.jpg',
    date: 1712645417,
    likes: 400,
    type: 1,
  },
  {
    id: 4,
    name: 'Banana Drink',
    ingredients: [
      '500g boneless chicken breast, sliced',
      '2 cups broccoli florets',
      '1 bell pepper, thinly sliced',
      '3 cloves garlic, minced',
      '2 tablespoons soy sauce',
      '1 tablespoon oyster sauce',
      '1 teaspoon sesame oil',
      '1 tablespoon vegetable oil',
      'Salt and pepper to taste',
      'Cooked rice for serving',
    ],
    image: '/assets/Img/food/f4.jpg',
    date: 1712645418,
    likes: 567,
    type: 3,
  },
  {
    id: 5,
    name: 'Savory Chicken Stir-Fry',
    ingredients: [
      '500g boneless chicken breast, sliced',
      '2 cups broccoli florets',
      '1 bell pepper, thinly sliced',
      '3 cloves garlic, minced',
      '2 tablespoons soy sauce',
      '1 tablespoon oyster sauce',
      '1 teaspoon sesame oil',
      '1 tablespoon vegetable oil',
      'Salt and pepper to taste',
      'Cooked rice for serving',
    ],
    image: '/assets/Img/food/f13.jpg',
    date: 1712645418,
    likes: 150,
    type: 0,
  },
  {
    id: 6,
    name: 'Vegetarian Quinoa Salad',
    ingredients: [
      '1 cup quinoa, cooked',
      '1 cup cherry tomatoes, halved',
      '1 cucumber, diced',
      '1/2 cup red onion, finely chopped',
      '1/4 cup feta cheese, crumbled',
      '2 tablespoons olive oil',
      '1 tablespoon balsamic vinegar',
      'Salt and pepper to taste',
    ],
    image: '/assets/Img/food/f5.jpg',
    date: 1712645419,
    likes: 120,
    type: 2,
  },
  {
    id: 7,
    name: 'Sushi Rolls',
    ingredients: [
      '2 cups sushi rice, cooked',
      'Nori sheets',
      'Fresh fish (salmon, tuna, etc.), thinly sliced',
      'Cucumber, julienned',
      'Avocado, sliced',
      'Soy sauce for dipping',
      'Wasabi and pickled ginger for serving',
    ],
    image: '/assets/Img/food/f6.jpg',
    date: 1712645420,
    likes: 300,
    type: 2,
  },
  {
    id: 8,
    name: 'Mango Tango Smoothie',
    ingredients: [
      '1 ripe mango, peeled and diced',
      '1 cup Greek yogurt',
      '1/2 cup orange juice',
      '1 tablespoon honey',
      'Ice cubes',
    ],
    image: '/assets/Img/food/f7.jpg',
    date: 1712645421,
    likes: 80,
    type: 3,
  },
  {
    id: 9,
    name: 'Spinach and Feta Stuffed Chicken Breast',
    ingredients: [
      '4 boneless, skinless chicken breasts',
      '2 cups fresh spinach, chopped',
      '1/2 cup feta cheese, crumbled',
      '2 cloves garlic, minced',
      '1 teaspoon dried oregano',
      'Salt and pepper to taste',
      '2 tablespoons olive oil',
    ],
    image: '/assets/Img/food/f8.jpg',
    date: 1712645422,
    likes: 180,
    type: 0,
  },
  {
    id: 10,
    name: 'Chocolate Avocado Mousse',
    ingredients: [
      '2 ripe avocados',
      '1/2 cup cocoa powder',
      '1/2 cup maple syrup or honey',
      '1 teaspoon vanilla extract',
      'A pinch of salt',
      'Fresh berries for garnish',
    ],
    image: '/assets/Img/food/f9.jpg',
    date: 1712645423,
    likes: 250,
    type: 4,
  },
  {
    id: 11,
    name: 'Caprese Salad Skewers',
    ingredients: [
      'Cherry tomatoes',
      'Fresh mozzarella balls',
      'Fresh basil leaves',
      'Balsamic glaze for drizzling',
      'Salt and pepper to taste',
    ],
    image: '/assets/Img/food/f10.jpg',
    date: 1712645424,
    likes: 120,
    type: 2,
  },
  {
    id: 12,
    name: 'Mushroom Risotto',
    ingredients: [
      '1 cup Arborio rice',
      '4 cups vegetable broth, heated',
      '1 cup mushrooms, sliced',
      '1/2 cup dry white wine',
      '1/2 cup Parmesan cheese, grated',
      '1 onion, finely chopped',
      '2 tablespoons butter',
      '2 tablespoons olive oil',
      'Salt and pepper to taste',
    ],
    image: '/assets/Img/food/f11.jpg',
    date: 1712645425,
    likes: 180,
    type: 2,
  },
  {
    id: 13,
    name: 'Grilled Salmon with Lemon-Dill Sauce',
    ingredients: [
      '4 salmon fillets',
      '1/4 cup fresh dill, chopped',
      'Juice of 1 lemon',
      '2 tablespoons olive oil',
      '2 cloves garlic, minced',
      'Salt and pepper to taste',
    ],
    image: '/assets/Img/food/f12.jpg',
    date: 1712645426,
    likes: 220,
    type: 1,
  },
  {
    id: 14,
    name: 'Vegetable Stir-Fry with Tofu',
    ingredients: [
      '1 block firm tofu, cubed',
      'Assorted vegetables (broccoli, bell peppers, carrots), sliced',
      '2 tablespoons soy sauce',
      '1 tablespoon hoisin sauce',
      '1 tablespoon sesame oil',
      '2 cloves garlic, minced',
      '1 tablespoon ginger, grated',
      'Cooked rice for serving',
    ],
    image: '/assets/Img/food/f17.jpg',
    date: 1712645427,
    likes: 150,
    type: 0,
  },
  {
    id: 15,
    name: 'Pesto Chicken Penne Pasta',
    ingredients: [
      '2 cups penne pasta, cooked',
      '1 lb chicken breast, cooked and diced',
      '1 cup cherry tomatoes, halved',
      '1/2 cup black olives, sliced',
      '1/4 cup pine nuts',
      '1/2 cup fresh basil pesto',
      'Salt and pepper to taste',
      'Grated Parmesan cheese for serving',
    ],
    image: '/assets/Img/food/f14.jpg',
    date: 1712645428,
    likes: 180,
    type: 2,
  },
  {
    id: 16,
    name: 'Ginger Garlic Shrimp Stir-Fry',
    ingredients: [
      '1 lb shrimp, peeled and deveined',
      '2 cups broccoli florets',
      '1 red bell pepper, sliced',
      '3 tablespoons soy sauce',
      '1 tablespoon honey',
      '1 tablespoon ginger, minced',
      '2 cloves garlic, minced',
      '2 tablespoons vegetable oil',
      'Green onions for garnish',
      'Cooked rice for serving',
    ],
    image: '/assets/Img/food/f15.jpg',
    date: 1712645429,
    likes: 250,
    type: 1,
  },
  {
    id: 17,
    name: 'Mixed Berry Smoothie Bowl',
    ingredients: [
      '1 cup mixed berries (strawberries, blueberries, raspberries)',
      '1 frozen banana',
      '1/2 cup Greek yogurt',
      '1/4 cup granola',
      '1 tablespoon honey',
      'Chia seeds for topping',
    ],
    image: '/assets/Img/food/f16.jpg',
    date: 1712645430,
    likes: 120,
    type: 3,
  },
  {
    id: 18,
    name: 'Perfect Espresso',
    ingredients: [
      '2 shots of espresso',
      '1 tablespoon sugar (optional)',
      'Steamed milk (optional)',
      'Whipped cream (optional)',
      'Cocoa powder for garnish (optional)',
    ],
    image: '/assets/Img/food/f20.jpg',
    date: 1712645434,
    likes: 1000000,
    type: 0,
  },
  {
    id: 19,
    name: 'Iced Caramel Macchiato',
    ingredients: [
      '2 shots of espresso',
      '1 cup milk',
      '2 tablespoons caramel syrup',
      'Ice cubes',
      'Whipped cream (optional)',
    ],
    image: '/assets/Img/food/f22.jpg',
    date: 1712645436,
    likes: 0,
    type: 0,
  },
  {
    id: 20,
    name: 'Iced Caramel Macchiato',
    ingredients: [
      '2 shots of espresso',
      '1 cup milk',
      '2 tablespoons caramel syrup',
      'Ice cubes',
      'Whipped cream (optional)',
    ],
    image: '/assets/Img/food/f22.jpg',
    date: 1712645436,
    likes: 369,
    type: 0,
  },
  {
    id: 21,
    name: 'Iced Caramel Macchiato',
    ingredients: [
      '2 shots of espresso',
      '1 cup milk',
      '2 tablespoons caramel syrup',
      'Ice cubes',
      'Whipped cream (optional)',
    ],
    image: '/assets/Img/food/f22.jpg',
    date: 1712645436,
    likes: 0,
    type: 0,
  },
];

interface Recipe {
  id: number;
  name: string;
  ingredients: string[];
  image: string;
  date: number;
  likes: number;
  type: number;
}

export default recipes;
