// src/utils/recipes.ts
import { Recipe } from '@/models/recipe.model';

const recipes: Recipe[] = [
  {
    id: 1,
    name: 'Recipe 1',
    sections: [
      {
        name: 'Section 1',
        ingredients: [
          { name: 'Ingredient 1', quantity: '1 cup', kind: 'type' },
          { name: 'Ingredient 2', quantity: '2 tbsp', kind: 'type' },
        ],
        preparationSteps: [
          { description: 'Step 1' },
          { description: 'Step 2' },
        ],
      },
    ],
    image: '/assets/Img/food/f1.jpg',
    date: 1622476800,
    likes: 100,
    type: 1,
  },
  {
    id: 1,
    name: 'Cheesy Risoli',
    sections: [
      {
        name: 'Main Ingredients',
        ingredients: [
          { name: 'Arborio rice', quantity: '1 cup', kind: '' },
          {
            name: 'Chicken or vegetable broth',
            quantity: '2 1/2 cups',
            kind: '',
          },
          { name: 'Grated Parmesan cheese', quantity: '1/2 cup', kind: '' },
          { name: 'Shredded mozzarella cheese', quantity: '1/2 cup', kind: '' },
          { name: 'Breadcrumbs', quantity: '1/2 cup', kind: '' },
          { name: 'Eggs, beaten', quantity: '2', kind: '' },
          { name: 'Salt and pepper', quantity: 'to taste', kind: '' },
          { name: 'Oil', quantity: 'for frying', kind: '' },
        ],
        preparationSteps: [
          {
            description:
              'In a saucepan, bring the chicken or vegetable broth to a simmer.',
          },
          {
            description:
              'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
          },
          { description: 'Remove from heat and let cool slightly.' },
          {
            description:
              'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
          },
        ],
      },
      {
        name: 'Frying',
        ingredients: [{ name: 'Oil', quantity: 'for frying', kind: '' }],
        preparationSteps: [
          {
            description:
              'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
          },
          { description: 'Heat oil in a frying pan over medium heat.' },
          {
            description:
              'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
          },
          { description: 'Remove from the pan and drain on paper towels.' },
        ],
      },
      {
        name: 'Serving',
        ingredients: [
          { name: 'Marinara sauce', quantity: 'for dipping', kind: '' },
        ],
        preparationSteps: [
          { description: 'Serve hot with marinara sauce for dipping.' },
        ],
      },
    ],
    image: '/assets/Img/food/f1.jpg',
    date: 1712645435,
    likes: 300,
    type: 2,
  },
  {
    id: 2,
    name: 'Delicious Pasta',
    sections: [
      {
        name: 'Main Ingredients',
        ingredients: [
          { name: 'Pasta', quantity: '200 grams', kind: '' },
          { name: 'Water', quantity: '2 cups', kind: '' },
          { name: 'Salt', quantity: '1 spoon', kind: '' },
          { name: 'Olive oil', quantity: '1 spoon', kind: '' },
          { name: 'Parmesan cheese', quantity: '100 grams', kind: '' },
          { name: 'Tomato sauce', quantity: '200 grams', kind: '' },
        ],
        preparationSteps: [
          {
            description:
              'In a saucepan, bring the chicken or vegetable broth to a simmer.',
          },
          {
            description:
              'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
          },
          { description: 'Remove from heat and let cool slightly.' },
          {
            description:
              'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
          },
          {
            description:
              'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
          },
          { description: 'Heat oil in a frying pan over medium heat.' },
          {
            description:
              'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
          },
          { description: 'Remove from the pan and drain on paper towels.' },
          { description: 'Serve hot with marinara sauce for dipping.' },
        ],
      },
    ],
    image: '/assets/Img/food/f2.jpg',
    date: 1796131033,
    likes: 200,
    type: 2,
  },
];

export default recipes;

//   {
//     id: 3,
//     name: 'Tasty Pizza',
//     ingredients: [
//       '1 pizza dough',
//       '1 cup of tomato sauce',
//       '1 cup of mozzarella cheese',
//       '100 grams of pepperoni',
//       '1 spoon of olive oil',
//       '1 pinch of salt',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f3.jpg',
//     date: 1332869487,
//     likes: 400,
//     type: 1,
//   },
//   {
//     id: 4,
//     name: 'Banana Drink',
//     ingredients: [
//       '500g boneless chicken breast, sliced',
//       '2 cups broccoli florets',
//       '1 bell pepper, thinly sliced',
//       '3 cloves garlic, minced',
//       '2 tablespoons soy sauce',
//       '1 tablespoon oyster sauce',
//       '1 teaspoon sesame oil',
//       '1 tablespoon vegetable oil',
//       'Salt and pepper to taste',
//       'Cooked rice for serving',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f4.jpg',
//     date: 1097192524,
//     likes: 567,
//     type: 3,
//   },
//   {
//     id: 5,
//     name: 'Savory Chicken Stir-Fry',
//     ingredients: [
//       '500g boneless chicken breast, sliced',
//       '2 cups broccoli florets',
//       '1 bell pepper, thinly sliced',
//       '3 cloves garlic, minced',
//       '2 tablespoons soy sauce',
//       '1 tablespoon oyster sauce',
//       '1 teaspoon sesame oil',
//       '1 tablespoon vegetable oil',
//       'Salt and pepper to taste',
//       'Cooked rice for serving',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f13.jpg',
//     date: 1547221076,
//     likes: 150,
//     type: 0,
//   },
//   {
//     id: 6,
//     name: 'Vegetarian Quinoa Salad',
//     ingredients: [
//       '1 cup quinoa, cooked',
//       '1 cup cherry tomatoes, halved',
//       '1 cucumber, diced',
//       '1/2 cup red onion, finely chopped',
//       '1/4 cup feta cheese, crumbled',
//       '2 tablespoons olive oil',
//       '1 tablespoon balsamic vinegar',
//       'Salt and pepper to taste',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f5.jpg',
//     date: 1209827125,
//     likes: 120,
//     type: 2,
//   },
//   {
//     id: 7,
//     name: 'Sushi Rolls',
//     ingredients: [
//       '2 cups sushi rice, cooked',
//       'Nori sheets',
//       'Fresh fish (salmon, tuna, etc.), thinly sliced',
//       'Cucumber, julienned',
//       'Avocado, sliced',
//       'Soy sauce for dipping',
//       'Wasabi and pickled ginger for serving',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f6.jpg',
//     date: 1755833373,
//     likes: 300,
//     type: 2,
//   },
//   {
//     id: 8,
//     name: 'Mango Tango Smoothie',
//     ingredients: [
//       '1 ripe mango, peeled and diced',
//       '1 cup Greek yogurt',
//       '1/2 cup orange juice',
//       '1 tablespoon honey',
//       'Ice cubes',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f7.jpg',
//     date: 1720561485,
//     likes: 80,
//     type: 3,
//   },
//   {
//     id: 9,
//     name: 'Spinach and Feta Stuffed Chicken Breast',
//     ingredients: [
//       '4 boneless, skinless chicken breasts',
//       '2 cups fresh spinach, chopped',
//       '1/2 cup feta cheese, crumbled',
//       '2 cloves garlic, minced',
//       '1 teaspoon dried oregano',
//       'Salt and pepper to taste',
//       '2 tablespoons olive oil',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f8.jpg',
//     date: 1558965673,
//     likes: 180,
//     type: 0,
//   },
//   {
//     id: 10,
//     name: 'Chocolate Avocado Mousse',
//     ingredients: [
//       '2 ripe avocados',
//       '1/2 cup cocoa powder',
//       '1/2 cup maple syrup or honey',
//       '1 teaspoon vanilla extract',
//       'A pinch of salt',
//       'Fresh berries for garnish',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f9.jpg',
//     date: 1295506571,
//     likes: 250,
//     type: 4,
//   },
//   {
//     id: 11,
//     name: 'Caprese Salad Skewers',
//     ingredients: [
//       'Cherry tomatoes',
//       'Fresh mozzarella balls',
//       'Fresh basil leaves',
//       'Balsamic glaze for drizzling',
//       'Salt and pepper to taste',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f10.jpg',
//     date: 1118328938,
//     likes: 120,
//     type: 2,
//   },

//   {
//     id: 12,
//     name: 'Mushroom Risotto',
//     ingredients: [
//       '1 cup Arborio rice',
//       '4 cups vegetable broth, heated',
//       '1 cup mushrooms, sliced',
//       '1/2 cup dry white wine',
//       '1/2 cup Parmesan cheese, grated',
//       '1 onion, finely chopped',
//       '2 tablespoons butter',
//       '2 tablespoons olive oil',
//       'Salt and pepper to taste',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f11.jpg',
//     date: 1817802032,
//     likes: 180,
//     type: 2,
//   },
//   {
//     id: 13,
//     name: 'Grilled Salmon with Lemon-Dill Sauce',
//     ingredients: [
//       '4 salmon fillets',
//       '1/4 cup fresh dill, chopped',
//       'Juice of 1 lemon',
//       '2 tablespoons olive oil',
//       '2 cloves garlic, minced',
//       'Salt and pepper to taste',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f12.jpg',
//     date: 1425928068,
//     likes: 220,
//     type: 1,
//   },
//   {
//     id: 14,
//     name: 'Vegetable Stir-Fry with Tofu',
//     ingredients: [
//       '1 block firm tofu, cubed',
//       'Assorted vegetables (broccoli, bell peppers, carrots), sliced',
//       '2 tablespoons soy sauce',
//       '1 tablespoon hoisin sauce',
//       '1 tablespoon sesame oil',
//       '2 cloves garlic, minced',
//       '1 tablespoon ginger, grated',
//       'Cooked rice for serving',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f17.jpg',
//     date: 1180770481,
//     likes: 150,
//     type: 0,
//   },
//   {
//     id: 15,
//     name: 'Pesto Chicken Penne Pasta',
//     ingredients: [
//       '2 cups penne pasta, cooked',
//       '1 lb chicken breast, cooked and diced',
//       '1 cup cherry tomatoes, halved',
//       '1/2 cup black olives, sliced',
//       '1/4 cup pine nuts',
//       '1/2 cup fresh basil pesto',
//       'Salt and pepper to taste',
//       'Grated Parmesan cheese for serving',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f14.jpg',
//     date: 1395191442,
//     likes: 180,
//     type: 2,
//   },
//   {
//     id: 16,
//     name: 'Ginger Garlic Shrimp Stir-Fry',
//     ingredients: [
//       '1 lb shrimp, peeled and deveined',
//       '2 cups broccoli florets',
//       '1 red bell pepper, sliced',
//       '3 tablespoons soy sauce',
//       '1 tablespoon honey',
//       '1 tablespoon ginger, minced',
//       '2 cloves garlic, minced',
//       '2 tablespoons vegetable oil',
//       'Green onions for garnish',
//       'Cooked rice for serving',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f15.jpg',
//     date: 1274322685,
//     likes: 250,
//     type: 1,
//   },
//   {
//     id: 17,
//     name: 'Mixed Berry Smoothie Bowl',
//     ingredients: [
//       '1 cup mixed berries (strawberries, blueberries, raspberries)',
//       '1 frozen banana',
//       '1/2 cup Greek yogurt',
//       '1/4 cup granola',
//       '1 tablespoon honey',
//       'Chia seeds for topping',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f16.jpg',
//     date: 998756736,
//     likes: 120,
//     type: 3,
//   },
//   {
//     id: 18,
//     name: 'Perfect Espresso',
//     ingredients: [
//       '2 shots of espresso',
//       '1 tablespoon sugar (optional)',
//       'Steamed milk (optional)',
//       'Whipped cream (optional)',
//       'Cocoa powder for garnish (optional)',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f20.jpg',
//     date: 1406036580,
//     likes: 1000000,
//     type: 0,
//   },
//   {
//     id: 19,
//     name: 'Iced Caramel Macchiato',
//     ingredients: [
//       '2 shots of espresso',
//       '1 cup milk',
//       '2 tablespoons caramel syrup',
//       'Ice cubes',
//       'Whipped cream (optional)',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f22.jpg',
//     date: 1265780807,
//     likes: 0,
//     type: 0,
//   },
//   {
//     id: 20,
//     name: 'Iced Caramel Macchiato',
//     ingredients: [
//       '2 shots of espresso',
//       '1 cup milk',
//       '2 tablespoons caramel syrup',
//       'Ice cubes',
//       'Whipped cream (optional)',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f22.jpg',
//     date: 1405109307,
//     likes: 369,
//     type: 0,
//   },
//   {
//     id: 21,
//     name: 'Iced Caramel Macchiato',
//     ingredients: [
//       '2 shots of espresso',
//       '1 cup milk',
//       '2 tablespoons caramel syrup',
//       'Ice cubes',
//       'Whipped cream (optional)',
//     ],
//     instructions: [
//       'In a saucepan, bring the chicken or vegetable broth to a simmer.',
//       'Add the arborio rice and cook until the rice is tender and the liquid is absorbed, about 20 minutes.',
//       'Remove from heat and let cool slightly.',
//       'Stir in the grated Parmesan cheese, shredded mozzarella cheese, breadcrumbs, beaten eggs, salt, and pepper until well combined.',
//       'Take a spoonful of the mixture and form it into a ball, then flatten it slightly to form a disc.',
//       'Heat oil in a frying pan over medium heat.',
//       'Fry the risoli until golden brown and crispy on both sides, about 2-3 minutes per side.',
//       'Remove from the pan and drain on paper towels.',
//       'Serve hot with marinara sauce for dipping.',
//     ],
//     image: '/assets/Img/food/f22.jpg',
//     date: 1405109307,
//     likes: 0,
//     type: 0,
//   },
// ];

// interface Recipe {
//   id: number;
//   name: string;
//   ingredients: string[];
//   instructions: string[];
//   image: string;
//   date: number;
//   likes: number;
//   type: number;
// }
